# About Me

[[Evening](~/MADA-course/patrickkaggwa-MADA-portfolio/images/personal.png)](~/MADA-course/patrickkaggwa-MADA-portfolio/images)

I am first year PhD, concentration Epidemiology under Global Health Institute with background in computer Hardware, open source systems, Network design and deployments, docker containerization, Linux and Health Informatics.

### Background and Research Interests

I hold a Bachelor of Science in Computer Science and Masters in Health Informatics with research interest around data science, AI and the intersection of technology and health. I currently work with Dr. Christopher Whalen and Dr. Juliet Sekandi under the Global Health Institute and they focus on TB research in Africa specifically Uganda.

I am deeply engaged in projects that involve the application of mobile digital technologies to enhance data collection, monitoring, and adherence in TB and also using using watches in collection of mobility data for participants at risk of LTBI.

### Data Analysis Experience

My data analysis skills are at the beginners level but now with knowledge in R acquired in EPID8500 and SAS am motivated in improving my analysis skills.

### MADA Course Expectations

I hope to improve my R programming and my data analysis skills using tools to in the Modern Applied Data Analysis course. I expect to get skills to help my kick start towards my data science and AI career.

[!Useful link on Quarto](https://www.youtube.com/watch?v=_f3latmOhew)
